# Generated by Django 2.2.11 on 2021-02-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('task', models.CharField(default='', max_length=500)),
                ('longitude', models.CharField(default='', max_length=100)),
                ('latitude', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
